name: MERN Stack CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Backend tests and build
  backend-ci:
    runs-on: ubuntu-latest
    
    services:
      # Set up MongoDB for testing
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
          
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: './server/pnpm-lock.yaml'

      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install backend dependencies
        run: |
          cd server
          pnpm install
      
      - name: Run backend linting
        run: |
          cd server
          pnpm run lint
      
      - name: Run backend tests
        run: |
          cd server
          pnpm test
        env:
          CI: true
          MONGODB_URI: mongodb://localhost:27017/test
          JWT_SECRET: test_secret_for_ci
      
      - name: Build backend
        run: |
          cd server
          pnpm run build --if-present

  # Frontend tests and build
  frontend-ci:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: './client/pnpm-lock.yaml'

      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install frontend dependencies
        run: |
          cd client
          pnpm install
      
      - name: Run frontend linting
        run: |
          cd client
          pnpm run lint
      
      - name: Run frontend tests
        run: |
          cd client
          pnpm test
        env:
          CI: true
      
      - name: Build frontend
        run: |
          cd client
          pnpm run build
      
      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: client/dist
          retention-days: 1

  # Deploy backend to Render
  deploy-backend:
    needs: [backend-ci, frontend-ci]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

  # Deploy frontend to Vercel
  deploy-frontend:
    needs: [backend-ci, frontend-ci]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Download frontend build artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: client/dist
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./client
          vercel-args: '--prod'

  # Run health checks after deployment
  health-check:
    needs: [deploy-backend, deploy-frontend]
    runs-on: ubuntu-latest
    
    steps:
      - name: Check backend health
        uses: jtalk/url-health-check-action@v3
        with:
          url: ${{ secrets.BACKEND_URL }}/api/health
          max-attempts: 3
          retry-delay: 5s
      
      - name: Check frontend
        uses: jtalk/url-health-check-action@v3
        with:
          url: ${{ secrets.FRONTEND_URL }}
          max-attempts: 3
          retry-delay: 5s 